[build]
functions = "/functions"
command = "npm run"

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/home"
  status = 200
[[redirects]]
  from = "/products"
  to = "/.netlify/functions/products"
  status = 200
[[redirects]]

  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
